
name: CI

on:
  push:
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create hotfix version
        run: |
           echo "HOTFIX_RELEASE=$(echo $GITHUB_REF | awk -F/ '{print $4}').hotfix.${{ github.event.inputs.hotfix }}" >> $GITHUB_ENV
           echo ${{ env.HOTFIX_RELEASE }}
